[config]
schemaVersion = "0.0.1"

[package]
namespace = "DisplayEquippedUpgrades"
name = "DisplayEquippedUpgrades"
description = "This is a mod for Mycopunk that makes equipped upgrades display differently in the upgrade screen."
websiteUrl = "https://github.com/Molaiom/Mycopunk_DisplayEquippedUpgrades"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/DisplayEquippedUpgrades.dll"
target = "BepInEx/plugins/DisplayEquippedUpgrades.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://github.com/Molaiom/Mycopunk_DisplayEquippedUpgrades"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]


